export const projects = [
	{
		title: 'Paws & Tails',
		imgUrl: '/paws-tails.png',
		tags: [
			'Nextjs',
			'PostgreSQL',
			'TypeScript',
			'Prisma',
			'Tailwind',
			'shadcn',
			'NextAuth',
			'Stripe',
		],
		link: 'https://github.com/Zurisaday01/paws-tails',
	},
	{
		title: 'AttendHub',
		imgUrl: '/attendhub.png',
		tags: [
			'.NET 9.0',
			'Nextjs',
			'PostgreSQL',
			'TypeScript',
			'Tailwind',
			'shadcn',
			'Docker',
			'Jenkins',
			'Entity Framework',
			'Microservices',
		],
		link: 'https://github.com/Zurisaday01/attendHub',
	},
	{
		title: 'E-Shoppe',
		imgUrl: '/e-shoppe.png',
		tags: ['React', 'Tailwind', 'Redux'],
		link: 'https://github.com/Zurisaday01/e-shoppe',
	},
	{
		title: 'Forms Mastery',
		imgUrl: '/forms-mastery.png',
		tags: [
			'Nextjs',
			'Tailwind',
			'shadcn',
			'TypeScript',
			'PostgreSQL',
			'Prisma',
			'TanStack Query',
		],
		link: 'https://github.com/Zurisaday01/forms-mastery',
	},
	{
		title: 'Spend Sage',
		imgUrl: '/spend-sage.png',
		tags: [
			'React',
			'Tailwind',
			'shadcn',
			'TypeScript',
			'Supabase',
			'RTK Query',
			'Redux',
		],
		link: 'https://github.com/Zurisaday01/spend-sage',
	},
	{
		title: 'Vault Movies',
		imgUrl: '/vault.png',
		tags: ['React', 'Tailwind', 'shadcn', 'TypeScript'],
		link: 'https://github.com/Zurisaday01/vault-movies',
	},
	{
		title: 'Hoop',
		imgUrl: '/hoop.png',
		tags: ['Nextjs', 'Tailwind', 'Clerk', 'shadcn', 'TypeScript'],
		link: 'https://github.com/Zurisaday01/hoop',
	},
	{
		title: 'Fast React Pizza',
		imgUrl: '/fast-pizza.png',
		tags: ['React', 'Tailwind'],
		link: 'https://github.com/Zurisaday01/react-project-redux',
	},
	{
		title: 'Quidditch Quizz',
		imgUrl: '/quizz.png',
		tags: ['React', 'CSS'],
		link: 'https://github.com/Zurisaday01/quidditch-reducer',
	},
	{
		title: 'Pups API',
		imgUrl: '/pups.png',
		tags: ['MongoDB', 'Node.js', 'Express.js'],
		link: 'https://github.com/Zurisaday01/pawsome-pups-server',
	},
];
